# fly.toml app configuration file generated for khoi-pokedex on 2023-11-16T11:39:26+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "khoi-pokedex"
primary_region = "syd"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  processes = ["app"]
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.16.0"